/* Configure os dois valores abaixo antes de publicar. */
const GAS_URL = 'https://script.google.com/macros/s/AKfycbx0RehqFX0xhbjbpXBFaWUDVG1n8YkjAsWqL8I6tVP0MnOfjWR51XUhLRteXzUvl8LG/exec';
const DB = 'turismo-atendimentos-v1', STORE = 'pendentes', OPT = 'opcoes';
const $ = id => document.getElementById(id); let options, busy = false;
const db = new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{r.result.createObjectStore(STORE,{keyPath:'idEnvio'});r.result.createObjectStore(OPT);};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function tx(store,mode,fn){const d=await db,t=d.transaction(store,mode),s=t.objectStore(store);const v=fn(s);return new Promise((res,rej)=>{t.oncomplete=()=>res(v);t.onerror=()=>rej(t.error);});}
const readOpt=()=>tx(OPT,'readonly',s=>new Promise(r=>{const q=s.get('current');q.onsuccess=()=>r(q.result);})); const saveOpt=x=>tx(OPT,'readwrite',s=>s.put(x,'current'));
const allPending=()=>tx(STORE,'readonly',s=>new Promise(r=>{const q=s.getAll();q.onsuccess=()=>r(q.result||[]);})); const putPending=x=>tx(STORE,'readwrite',s=>s.put(x)); const delPending=id=>tx(STORE,'readwrite',s=>s.delete(id));
function message(t,error=false){$('msg').textContent=t||'';$('msg').className='msg '+(error?'error':'ok');}function selection(n){const e=document.querySelector(`input[name="${n}"]:checked`);return e&&e.value||''}function fill(el,list,first){el.replaceChildren(new Option(first,''));list.forEach(x=>el.add(new Option(x,x)));}function fillInfo(groups){const e=$('info');e.replaceChildren(new Option('Selecione a informação',''));[['Principais',groups.principais],['Outros',groups.outros]].forEach(([name,list])=>{const g=document.createElement('optgroup');g.label=name;(list||[]).forEach(x=>g.append(new Option(x,x)));e.append(g);});}
function renderOptions(){if(!options)return;fill($('pais'),options.paises,'Selecione o país');fill($('estado'),options.estados,'Selecione o estado');fillInfo(options.informacoes);$('info').disabled=false;$('save').disabled=false;adjust();}
function adjust(){const tipo=selection('tipo'),nac=selection('nac'),cur=tipo==='Curitiba e Região Metropolitana',br=nac==='Brasileiro';if(cur){document.querySelector('input[name="nac"][value="Brasileiro"]').checked=true;}const n=selection('nac');$('pais').disabled=!options||!tipo||!n||cur||n==='Brasileiro';$('pais').value=(cur||n==='Brasileiro')?'Brasil':$('pais').value;$('estado').disabled=!options||!(cur||(!cur&&n==='Brasileiro'));if(cur)$('estado').value='Paraná';if(!(cur||n==='Brasileiro'))$('estado').value='';$('outroBox').classList.toggle('hide',$('info').value!=='Outros');if($('info').value!=='Outros')$('outro').value='';}
function b64(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function rpc(action,payload){return new Promise((resolve,reject)=>{if(!navigator.onLine)return reject(new Error('Sem conexão.'));const nonce=crypto.randomUUID().replace(/-/g,'');const timeout=setTimeout(()=>{cleanup();reject(new Error('A sincronização não respondeu; o registro continuará pendente.'));},30000);function cleanup(){clearTimeout(timeout);window.removeEventListener('message',receive);}function receive(e){if(e.source!==$('bridge').contentWindow||!e.data||e.data.tipo!=='atendimento-pwa'||e.data.resposta.nonce!==nonce)return;cleanup();e.data.resposta.sucesso?resolve(e.data.resposta):reject(new Error(e.data.resposta.erro||'Falha no servidor.'));}window.addEventListener('message',receive);const f=document.createElement('form');f.method='POST';f.action=GAS_URL;f.target='bridge';[['action',action],['payload',b64(payload||{})],['origin',location.origin],['nonce',nonce]].forEach(([n,v])=>{const i=document.createElement('input');i.type='hidden';i.name=n;i.value=v;f.append(i);});document.body.append(f);f.submit();f.remove();});}
async function refreshOptions(){try{const r=await rpc('opcoes',{});options=r.opcoes;await saveOpt(options);renderOptions();}catch(e){if(!options)message('Sem opções locais. Conecte uma vez à internet para preparar este tablet.',true);}}
async function count(){const n=(await allPending()).length;$('pending').textContent=`Pendentes: ${n}`;}function net(){const on=navigator.onLine;$('network').textContent=on?'● Online':'● Offline';$('network').className=on?'':'offline';}
async function sync(){if(busy||!navigator.onLine)return;busy=true;try{for(const x of await allPending()){try{await rpc('sincronizar',x);await delPending(x.idEnvio);}catch(e){console.warn('Pendente mantido:',e.message);break;}}await count();}finally{busy=false;}}
function newId(){return crypto.randomUUID?crypto.randomUUID().replace(/-/g,''):`${Date.now()}${Math.random().toString(36).slice(2)}`;}
$('form').addEventListener('submit',async e=>{e.preventDefault();if(!options)return message('As opções do formulário ainda não estão disponíveis.',true);const tipo=selection('tipo'),nac=selection('nac');const d={idEnvio:newId(),criadoEm:new Date().toISOString(),nome:$('nome').value.trim(),tipoAtendimento:tipo,nacionalidade:nac,paisOrigem:$('pais').value,estadoOrigem:$('estado').value,informacao:$('info').value,informacaoOutro:$('outro').value.trim(),observacoes:$('obs').value.trim()};if(!d.nome||!tipo||!nac||!d.paisOrigem||!d.informacao||((tipo==='Curitiba e Região Metropolitana'||nac==='Brasileiro')&&!d.estadoOrigem)||(d.informacao==='Outros'&&!d.informacaoOutro))return message('Preencha todos os campos obrigatórios.',true);await putPending(d);await count();$('form').reset();adjust();message('Atendimento salvo neste tablet.');sync();});
document.querySelectorAll('input[name="tipo"],input[name="nac"]').forEach(x=>x.addEventListener('change',adjust));$('info').addEventListener('change',adjust);window.addEventListener('online',()=>{net();refreshOptions();sync();});window.addEventListener('offline',net);(async()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');net();options=await readOpt();renderOptions();await count();refreshOptions();sync();})();
